name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      
  Test:
    runs-on: ubuntu-latest
    env:
      CI: true
    needs: Install
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: actions/node-setup@v3
        with:
          cache: npm
      - run: npm ci --offline
      - run: npm run test:lint
      - run: npm run test:deps
      - run: npm run test:types
      - run: npm run test:unit:coverage
      - run: npm run test:e2e:ci
      - name: Cache test report
        uses: actions/cache@v3
        env:
          cache-name: cache-test-results
        with:
          path: coverage/**
          key: build-${{ env.cache-name }}-${{ github.sha }}
        

  Sonar:
    runs-on: ubuntu-latest
    needs: [Install, Test]
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/cache@v3
        env:
          cache-name: cache-test-results
        with:
          path: coverage/
          key: build-${{ env.cache-name }}-${{ github.sha }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build:
    runs-on: ubuntu-latest
    needs: Install
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/node-setup@v3
        with:
          cache: npm
      - run: npm ci --offline
      - run: npm run build

  Storybook:
    runs-on: ubuntu-latest
    needs: Install
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/node-setup@v3
        with:
          cache: npm
      - run: npm ci --offline
      - run: npm run test:playground:smoketest
